# 置換変数
substitutions:
  _REGION: asia-northeast1 # デプロイリージョン
  _ALG_NAME: iforest # アルゴリズム名
  _IMAGE_TAG: latest # イメージタグ

steps:
  # 1) KFP 共通イメージをビルド
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/ml/kfp:latest",
        "-f",
        "docker/kfp/Dockerfile",
        ".",
      ]

  # 2) Docker イメージをビルド（アルゴリズム別の Dockerfile を使用）
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/ml/${_ALG_NAME}-train:${_IMAGE_TAG}",
        "-f",
        "docker/${_ALG_NAME}/Dockerfile",
        ".",
      ]
  # 3) Artifact Registry へイメージをプッシュ
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/ml/${_ALG_NAME}-train:${_IMAGE_TAG}",
      ]
  # 4) Vertex AI Custom Job を作成しトレーニングを開始
  - name: "gcloud"
    entrypoint: "bash"
    args:
      [
        "-c",
        "gcloud ai custom-jobs create --region=$_REGION --display-name=${_ALG_NAME}-train --worker-pool-spec=machine-type=n1-standard-4,replica-count=1,container-image-uri=$_REGION-docker.pkg.dev/$PROJECT_ID/ml/${_ALG_NAME}-train:${_IMAGE_TAG}",
      ]
