steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$_REGION-docker.pkg.dev/$PROJECT_ID/ml/iforest-train:latest",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      ["push", "$_REGION-docker.pkg.dev/$PROJECT_ID/ml/iforest-train:latest"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - ai
      - custom-jobs
      - create
      - --region=$_REGION
      - --display-name=iforest-train
      - --worker-pool-spec=machine-type=n1-standard-4,container-image-uri=$_REGION-docker.pkg.dev/$PROJECT_ID/ml/iforest-train:latest

substitutions:
  _REGION: asia-northeast1
