# dev へのプラン実行用
name: "Terraform Plan (dev)"

# パーミッション設定
permissions:
  contents: read # ソースチェックアウト用
  id-token: write # OIDC トークン発行用
  pull-requests: write # コメント用

on:
  pull_request:
    branches: [develop]
    paths: ["terraform/**"]
  workflow_dispatch: # UI から手動トリガー可能

jobs:
  call-plan:
    uses: ./.github/workflows/_terraform-plan.yml
    with:
      workspace: dev
      environment: dev
    secrets: inherit
