# prod への手動デプロイ用
name: "Terraform Apply (prod)"

# パーミッション設定
permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch: # UI から手動トリガー可能

jobs:
  apply:
    runs-on: ubuntu-latest
    environment: prod
    concurrency:
      group: terraform-prod
      cancel-in-progress: false # デプロイ中はキャンセルしない
    env:
      TF_WORKSPACE: prod
    steps:
      # 1) リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) GCP 認証：Auth
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider
          service_account: tf-svc@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com

      # 3) Terraform をセットアップ
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: 1.11.4

      # 4) Terraform の初期化
      - name: Initialize Terraform
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="bucket=terraform-state-portfolio-vertex-ai-dex" \
            -backend-config="prefix=vertex-ai/prod" \
            -input=false

      # 5) ワークスペースの指定
      - name: Select workspace
        working-directory: terraform
        run: terraform workspace select prod || terraform workspace new prod

      # 6) Terraform の適用
      - name: Apply Terraform
        working-directory: terraform
        run: |
          terraform apply \
            -var-file=envs/prod/terraform.tfvars \
            -var "project_id=${{ secrets.PROJECT_ID }}" \
            -var "env_suffix=prod" \
            -input=false \
            -auto-approve \
            -lock-timeout=300s
