# prod へのプラン実行用
name: "Terraform Plan (prod)"

# パーミッション設定
permissions:
  contents: read # ソースチェックアウト用
  id-token: write # OIDC トークン発行用
  pull-requests: write # コメント用

on:
  pull_request:
    branches: [main]
    paths: ["infra/**"]

jobs:
  call-plan:
    uses: ./.github/workflows/_terraform-plan.yml
    with:
      workspace: prod
    secrets: inherit
